apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskline-frontend
  labels:
    app: taskline-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskline-frontend
  template:
    metadata:
      labels:
        app: taskline-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: taskline-frontend
          image: FRONTEND_IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-runtime-config
              mountPath: /usr/share/nginx/html/app-config.js
              subPath: app-config.js
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: frontend-runtime-config
          configMap:
            name: taskline-frontend-config
