apiVersion: v1
kind: Service
metadata:
  name: taskline-frontend-service
  labels:
    app: taskline-frontend

spec:
  type: LoadBalancer

  selector:
    app: taskline-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80